version: '3.8'

services:

  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - $HOME/z/github/tzaffi/gophercises/urlshort/migrate:/migrate_urlshort
      - pg_data:/var/lib/postgresql/data/

volumes:
  pg_data: